### ISSUE TITLE
FullCalendarModule does not have 'ɵmod' property

### ISSUE THREAD

**Issue by phristov** [fullcalendar/fullcalendar-angular#395]
How to reproduce it:

Angular 13.2.6

```
yarn add @fullcalendar/angular @fullcalendar/daygrid
```

npm
```
"@fullcalendar/angular": "^5.10.2",
"@fullcalendar/daygrid": "^5.10.1",
```
module
```
import dayGridPlugin from '@fullcalendar/daygrid';

FullCalendarModule.registerPlugins([
  dayGridPlugin,
])
```

component
```
import { CalendarOptions } from '@fullcalendar/angular';

calendarOptions: CalendarOptions = {
   initialView: 'dayGridMonth'
};
```

html
```
<full-calendar [options]='calendarOptions'></full-calendar>
```

Everything is working fine, I can see the calendar. 

```
yarn add @fullcalendar/interaction
```
npm
```
"@fullcalendar/interaction": "^5.10.1",
"@fullcalendar/angular": "^5.10.2",
"@fullcalendar/daygrid": "^5.10.1",
```
module
```
import dayGridPlugin from '@fullcalendar/daygrid';
import interactionPlugin from '@fullcalendar/interaction';

FullCalendarModule.registerPlugins([
  dayGridPlugin,
  interactionPlugin
])

```
component
```
import { CalendarOptions } from '@fullcalendar/angular';

calendarOptions: CalendarOptions = {
   initialView: 'dayGridMonth'
};
```

I get the following error

```
core.mjs:6485 ERROR Error: Uncaught (in promise): Error: Type FullCalendarModule does not have 'ɵmod' property.
Error: Type FullCalendarModule does not have 'ɵmod' property.
    at getNgModuleDef (core.mjs:1139:1)
    at recurse (core.mjs:21757:1)
    at recurse (core.mjs:21768:1)
    at registerNgModuleType (core.mjs:21753:1)
    at new NgModuleFactory (core.mjs:21875:1)
    at Compiler.compileModuleSync (core.mjs:25129:1)
    at Compiler.compileModuleAsync (core.mjs:25135:1)
    at router.mjs:3984:43
    at doInnerSub (mergeInternals.js:19:18)
    at outerNext (mergeInternals.js:14:1)
    at resolvePromise (zone.js:1211:1)
    at resolvePromise (zone.js:1165:1)
    at zone.js:1278:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25535:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:1)
    at invokeTask (zone.js:1648:1)
```

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
